apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: default
type: Opaque
data:
  # Replace the value below with: echo -n "hf_your_real_token" | base64
  token: "<BASE64_ENCODED_HF_TOKEN>"