apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-8b-pv
spec:
  capacity:
    storage: 35Gi  # Adjust this based on your storage requirements
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /mnt/data/llama-8b  # Path to the directory created on the VM's local storage
