apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-8b
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
  storageClassName: default
  volumeMode: Filesystem