apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-8b
  namespace: default
  labels:
    app: llama-8b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-8b
  template:
    metadata:
      labels:
        app: llama-8b
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: llama-8b
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "4Gi"
      containers:
      - name: llama-8b
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve meta-llama/Llama-3.1-8B-Instruct --dtype half --trust-remote-code --max-model-len 1024 "
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "10"
            memory: 20G
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: 6G
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        startupProbe:  # Added critical startup probe
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 15
          failureThreshold: 12  # 180s total
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 240
          periodSeconds: 30
