apiVersion: v1
kind: Service
metadata:
  name: llama-8b
  namespace: default
spec:
  ports:
  - name: http-llama-8b
    port: 80
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: llama-8b
  sessionAffinity: None
  type: ClusterIP


